####################################################################################################
## General

HOST: 0.0.0.0
PORT: 8055
PUBLIC_URL: /

####################################################################################################
## File Storage

STORAGE_LOCATIONS: local

STORAGE_LOCAL_DRIVER: local
STORAGE_LOCAL_ROOT: ./uploads

####################################################################################################
## Security

KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263

ADMIN_EMAIL: grant@atriustech.com
ADMIN_PASSWORD: directus
